version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_bolt_advertised__address=localhost
      - NEO4J_dbms_connector_http_advertised__address=localhost
      - NEO4J_dbms_connector_https_advertised__address=localhost
      - NEO4JLABS_PLUGINS=["apoc"]
    expose:
      - 7687
      - 7474
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs
    - $HOME/neo4j/plugins:/plugins
    - "./import:/import"

  birdwatcher:
    build: .
    command: python3 src/main.py
    volumes:
      - "./pic:/birdwather_app/pic"
      # This one is to save database to, than see the file in host filesystem
      - "./import:/birdwather_app/import"
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/birdwathcer

    user: qtuser
    environment:
     - DISPLAY=$DISPLAY
    depends_on:
      - neo4j