version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_bolt_advertised__address=localhost
      - NEO4J_dbms_connector_http_advertised__address=localhost
      - NEO4J_dbms_connector_https_advertised__address=localhost
      - NEO4JLABS_PLUGINS=["apoc"]
    expose:
      - 7687
      - 7474
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs
#    - $HOME/neo4j/import:/import
    - $HOME/neo4j/plugins:/plugins
    - type: bind
      source: $HOST/home/mikhail/neo4j/import
      target: /import

  birdwatcher:
    build: .
    command: python3 src/main.py
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/birdwathcer
      # This one is to save database to, than see the file in host filesystem
#      - type: bind
#          source: $HOST/home/mikhail/neo4j/import
#          target: /import
    user: qtuser
    environment:
     - DISPLAY=$DISPLAY
    depends_on:
      - neo4j