version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_connector_bolt_advertised__address=localhost
      - NEO4J_dbms_connector_http_advertised__address=localhost
      - NEO4J_dbms_connector_https_advertised__address=localhost
    expose:
      - 7687
      - 7474
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/logs:/logs
    - $HOME/neo4j/import:/var/lib/neo4j/import
    - $HOME/neo4j/plugins:/plugins

  birdwatcher:
    build: .
    command: python3 src/main.py
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/birdwathcer
    user: qtuser
    environment:
     - DISPLAY=$DISPLAY
    depends_on:
      - neo4j